[connections.supabase]
SUPABASE_URL = "https://eqplgrbegwzeynnbcuep.supabase.co"
SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVxcGxncmJlZ3d6ZXlubmJjdWVwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgzNjU2MTEsImV4cCI6MjA3Mzk0MTYxMX0.wDSRvnb0BBi3qkrHIguL835Np4Kc-K0u_radUe6AixU"
SUPABASE_SERVICE_KEY = "temporary_service_key"

[app]
JWT_SECRET_KEY = "ymv_secret_key_2024_development"